project:
  type: book

book:
  title: "Quarto Coverage Tracking"
  subtitle: "Project Documentation"
  chapters:
    - index.qmd
    - spec.qmd
    - SPEC-0.0.2-v001.qmd
    - GUIDE-FOR-CONTENT-EDITORS-AND-TEACHERS.qmd

format:
  html:
    toc: true
    number-sections: true
